#!/usr/bin/env bash
# Auto-generated by /sdd:doctor init — lint hook for biome.
# Re-run /sdd:doctor init to regenerate, OR edit freely — init will skip a file that exists.
set -euo pipefail

# Read the PostToolUse JSON payload from stdin and pull out tool_input.file_path.
file_path="$(cat | python3 -c 'import json,sys; print(json.load(sys.stdin).get("tool_input",{}).get("file_path",""))' 2>/dev/null || true)"
[[ -z "$file_path" ]] && exit 0
[[ ! -f "$file_path" ]] && exit 0

ext="${file_path##*.}"

case "$ext" in
  ts|tsx|js|jsx|mjs|cjs|json)
    command -v npx >/dev/null 2>&1 || exit 0
    npx --no-install --quiet biome --version >/dev/null 2>&1 || exit 0   # tool absent → no-op
    if ! npx --no-install biome check "$file_path" 2>&1; then
      echo "❌ Biome failed for $file_path" >&2
      exit 2
    fi
    ;;
esac

exit 0
