#!/usr/bin/env bash
# Auto-generated by /sdd:doctor init — typecheck hook for tsc.
# Re-run /sdd:doctor init to regenerate, OR edit freely — init will skip a file that exists.
set -euo pipefail

# Read the PostToolUse JSON payload from stdin and pull out tool_input.file_path.
file_path="$(cat | python3 -c 'import json,sys; print(json.load(sys.stdin).get("tool_input",{}).get("file_path",""))' 2>/dev/null || true)"
[[ -z "$file_path" ]] && exit 0
[[ ! -f "$file_path" ]] && exit 0

ext="${file_path##*.}"

# tsc has no per-file mode under this project's config (Bundler resolution, extensionless
# imports) — check the whole project, gated on TS files only so non-TS edits stay fast.
case "$ext" in
  ts|tsx)
    command -v npx >/dev/null 2>&1 || exit 0
    npx --no-install --quiet tsc --version >/dev/null 2>&1 || exit 0   # tool absent → no-op
    if ! npx --no-install tsc --noEmit 2>&1; then
      echo "❌ tsc failed for $file_path" >&2
      exit 2
    fi
    ;;
esac

exit 0
